Feat: set Key Vault values
cal-itp/benefits pull request #1293
Opened 2023-02-23 15:55 UTC by angela-tran

Closes #1242 

Secret values from our `dev`, `test`, and `prod` data migrations have been added to their respective Key Vaults in Azure.

### Naming convention
From [Azure docs](https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-portal#add-a-secret-to-key-vault):
> The secret name must be unique within a Key Vault. The name must be a 1-127 character string, starting with a letter and containing only 0-9, a-z, A-Z, and -.

So the naming convention I used is to take the environment variable name, replace `_` with `-`, and make all characters lowercase.

### Changes in this PR
Our sample data migration file was missing a few environment variables that we introduced in our real data migrations, so I added them in this PR.

I also added documentation on how to set secrets in Key Vault and some helper scripts for running the Azure CLI command.

2023-02-24 01:29 UTC, thekaveman requested changes
Just some ordering in the bash helpers

2023-02-24 01:29 UTC, thekaveman commented on terraform/secrets/file.sh
> +if [ $# -ne 3 ]; then
I think this check needs to come before referencing `$1`, `$2`, `$3` if they are all required.

2023-02-24 01:29 UTC, thekaveman commented on terraform/secrets/value.sh
> +if [ $# -ne 3 ]; then
Same comment

2023-02-24 21:24 UTC, angela-tran commented
Fixed a bug where the incorrect arguments were being used -- this was because I "cleaned up" the script after I actually used it. It should be correct now. 🙏

2023-02-28 17:02 UTC, thekaveman requested changes

2023-02-28 17:42 UTC, angela-tran commented on terraform/secrets/file.sh
> +az keyvault secret set --vault-name "KV-CDT-PUB-CALITP-$env-001" --name $secret_name --file $file_path
Yep, I definitely can do that. Good catch, thank you 🙏

2023-02-28 17:52 UTC, angela-tran commented on terraform/secrets/file.sh
> +az keyvault secret set --vault-name "KV-CDT-PUB-CALITP-$env-001" --name $secret_name --file $file_path
Done in [88dcc89](https://github.com/cal-itp/benefits/pull/1293/commits/88dcc89ae2be57d3fa93772afdbc876dcf303349)

2023-03-02 16:23 UTC, thekaveman approved these changes
Looks great!

2023-03-02 17:21 UTC, merged