Chore: update release template
cal-itp/benefits pull request #1350
Opened 2023-04-05 15:37 UTC by angela-tran

Closes #1333 

This PR updates the release issue template to give details on updating configuration when releasing / deploying the Benefits app.

2023-04-10 22:37 UTC, angela-tran commented
@thekaveman @machikoyasuda Can you read over this and tell me if this list makes sense to you?

2023-04-10 23:21 UTC, thekaveman requested changes
You're right, this is harder than I expected!

I think the "staging target" thing is needlessly confusing and we can assume by the time we're releasing, `dev` has already been squared away / secrets configured / QA'd etc. 

Also, I think in #1284 we decided that the steps for hotfix are different enough that they warrant docs of their own; so...

Suggestions:

* Reformat into 2 lists: one for `regular`, one for `hotfix`
* Make the first step in `regular` something like "Ensure the `dev` branch and secrets are up to date", then bump the version etc. (i.e. we don't need individual steps for updating dev secrets etc.)
* Remove all the "if applicable" language

This feels overly complicated because we're trying to represent 2 flows in 1 list.

2023-04-27 19:23 UTC, angela-tran commented
Ready for re-review, whenever convenient

2023-04-27 21:25 UTC, thekaveman approved these changes
Looks good. I don't think we need this extra step/check-box but not a deal breaker.

2023-04-27 21:25 UTC, thekaveman commented on .github/ISSUE_TEMPLATE/release.yml
> +        - label: "**Apply hotfix to `dev`** (sub-steps below):"
```suggestion

```

2023-04-27 21:29 UTC, angela-tran commented
@thekaveman I settled on removing that extra step 😄 thanks for all your feedback on simplifying this template!

2023-04-27 21:31 UTC, thekaveman approved these changes
🚀

2023-04-27 21:32 UTC, merged