Fix: Update spanish tense for Login.gov modal
cal-itp/benefits pull request #1712
Opened 2023-09-07 20:45 UTC by machikoyasuda

closes #1709 

The rest of the Spanish copy on the app uses the formal usted tense (for pronouns, verbs). This PR updates the Login.gov modal from informal tu tense to formal usted tense.

2023-09-08 20:17 UTC, thekaveman requested changes
At least one more snuck in at the bottom: https://github.com/cal-itp/benefits/pull/1712/files#diff-748b0299f076e6e9a7c2a8bd1ecae94e02768b9c07bd8a84ddfa4ebdb62752fdR576

2023-09-11 17:30 UTC, machikoyasuda commented
@thekaveman Thanks for that catch! I searched thru the Spanish file to make sure there aren't any more `tu`s in there.

2023-09-11 19:10 UTC, thekaveman approved these changes
🇪🇸 ✔️

2023-09-11 19:21 UTC, merged

2023-10-11 12:59 UTC, afeld commented
Hey folks- I'm giving a talk about modern software delivery to some public policy students today and this was a great example for me to show. Thanks again for working in the open! 🌤️ 🙌

2023-10-11 15:09 UTC, thekaveman commented
Nice to see you @afeld!