Add SBMTD Mobility Pass vars to Terraform
cal-itp/benefits pull request #1779
Opened 2023-11-09 20:39 UTC by machikoyasuda

closes #1777

2023-11-09 21:48 UTC, thekaveman reviewed
Can you please confirm these are all added and configured in the 3 different environments (`dev`, `test`, `prod` Key Vaults in Azure?)

2023-11-15 18:01 UTC, machikoyasuda commented
Secrets status:
- Dev: Added all new variables for SBMTD, including FrontDoor URL for SBMTD Eligibility Server (Dev), added `mst-server-public-key-url`. Set `mobility-pass-verifier-active` to `True`. Removed `sever-public-key-url`.
- Test and Prod: Added all new variables for SBMTD, added `mst-server-public-key-url`, does not have FrontDoor URLs for Test/Prod envs for Eligibility Server. Set `mobility-pass-verifier-active` to `False`. Did NOT remove `sever-public-key-url` b/c it is still being used.

2023-11-15 21:47 UTC, machikoyasuda commented
@thekaveman @angela-tran Need to get this PR re-reviewed, before I can continue set up of SBMTD Mob Pass on Dev.

2023-11-15 22:19 UTC, angela-tran requested changes

2023-11-15 22:19 UTC, angela-tran commented on terraform/app_service.tf
> +    "MOBILITY_PASS_VERIFIER_API_AUTH_KEY"                  = "${local.secret_prefix}mobility-pass-verifier-api-auth-header)"
```suggestion
    "MOBILITY_PASS_VERIFIER_API_AUTH_KEY"                  = "${local.secret_prefix}mobility-pass-verifier-api-auth-key)"
```

2023-11-16 18:10 UTC, angela-tran approved these changes

2023-11-16 18:19 UTC, thekaveman approved these changes

2023-11-16 19:11 UTC, merged