Low-income use case
cal-itp/benefits pull request #1872
Opened 2024-02-03 01:27 UTC by indexing

2024-02-03 01:33 UTC, indexing commented
I still need to add the sequence diagram for this use case, but I'll do that as a change after this file is merged. 

Additionally, I'd like this to display alphabetically by name in the list of pathways. Is this a change I can make post-merge? Not sure how to do it before.

2024-02-03 01:40 UTC, thekaveman commented
@indexing the file is named `Low-income.md` which is why it is sorting above the all lowercase e.g. `agency-card.md`.

If you rename the file to be all lowercase like the rest, it will naturally sort.

2024-02-05 20:03 UTC, machikoyasuda commented on docs/enrollment-pathways/Low-income.md
> +- Benefit enrollment doesn’t require online accounts with private companies.
These benefits (for Benefits, hah) are the same for all eligibility types. But I guess it's okay to repeat them.

One benefit that is SPECIFIC to low-income is that by using CalFresh status, the rider does not have to go through another income verification process, and the transit agency does not have to create an income verification process that they have to then manage and get approved by their Board of Directors and so on. And what if every transit agency had a different definition of low income? This allows for potentially having the _same_ definition of "low income" across the state.

2024-02-05 20:38 UTC, thekaveman commented
I fully agree with all of @machikoyasuda's comments above!

2024-02-06 18:41 UTC, angela-tran commented on docs/enrollment-pathways/Low-income.md
> +5. The Cal-ITP Benefits app interfaces with the [California Department of Transportation](https://dot.ca.gov/) Identity Gateway (IdG) to verify benefit eligibility. The IdG uses personal information
The Benefits app interfaces with the California Department of Technology - https://cdt.ca.gov/. (Their shared abbreviation makes this a common mistake.)

2024-02-06 18:46 UTC, angela-tran reviewed
Thanks for all your work on this @indexing . I left one comment about a small typo.

2024-02-12 20:20 UTC, machikoyasuda commented on docs/enrollment-pathways/low-income.md
> +5. The Cal-ITP Benefits app interfaces with the [California Department of Transportation](https://dot.ca.gov/) Identity Gateway (IdG) to verify benefit eligibility. The IdG uses personal information
```suggestion
5. The Cal-ITP Benefits app interfaces with the [California Department of Technology](https://cdt.ca.gov/) [Identity Gateway (IdG)](https://digitalidstrategy.cdt.ca.gov/primary-elements.html) to verify benefit eligibility. The IdG uses personal information shared by [Login.gov](Login.gov) to verify Calfresh participation status.
```

2024-02-12 20:21 UTC, machikoyasuda requested changes
Everything looks good except for that last CDT/Caltrans link typo.

2024-02-14 20:34 UTC, machikoyasuda approved these changes

2024-02-14 20:34 UTC, merged