Add Lighthouse a11y testing to Test UI workflow
cal-itp/benefits pull request #202
Opened 2021-11-18 23:14 UTC by machikoyasuda

2021-11-18 23:51 UTC, thekaveman commented on .github/workflows/tests-ui.yml
> +name: UI automation and a11y Lighthouse tests
This is a little long, can we come up with a simpler name that captures it all?

(See the very bottom): 
![image](https://user-images.githubusercontent.com/1783439/142514784-56032a10-6a4b-477e-b644-5c2394c0d00c.png)

2021-11-18 23:55 UTC, thekaveman commented on .github/workflows/tests-ui.yml
> +name: UI automation and a11y Lighthouse tests
👍

2021-11-19 01:20 UTC, machikoyasuda commented
Ready for final review @thekaveman

2021-11-19 15:56 UTC, thekaveman requested changes
This looks awesome!! So cool you integrated with our existing UI test run!

I do have one piece of feedback on the "trying things out" type of commits. Those are great when you're not sure what is going to happen (esp. with GH Actions!), but can we please rebase to clean up the final PR before merging? I'd rather we don't clutter the history with those types of commits.

I did the exact same thing on #195 - had tons of commits changing one little thing, trying to make the workflow run. Once I got it, I went back and `squashed` those commits down into the "real" commits introducing "real" changes.

2021-11-19 18:59 UTC, machikoyasuda commented
@thekaveman Rebased :)

2021-11-19 19:57 UTC, thekaveman approved these changes
Amazing!

2021-11-19 20:34 UTC, merged