Feat: templates and copy for California State Transit
cal-itp/benefits pull request #2197
Opened 2024-07-03 19:51 UTC by thekaveman

This is our sample transit agency used for testing and demos.

Part of #2189

2024-07-03 21:20 UTC, thekaveman commented on benefits/locale/es/LC_MESSAGES/django.po
> +"No se le cobró nada hoy. Al abordar un autobús de MST, toque el lector con "
Small bug in our existing translation -- we had the `CST` slug in the `MST` copy!

2024-07-08 22:16 UTC, angela-tran requested changes
I think the templates look good - just some filenames typos I noticed

2024-07-08 23:35 UTC, thekaveman commented on benefits/eligibility/templates/eligibility/includes/selection-label--cst-agecy-card.html
Thank you for catching this!

2024-07-08 23:35 UTC, thekaveman commented on benefits/eligibility/templates/eligibility/start--cst-agecy-card.html
Thank you for catching this!

2024-07-09 00:43 UTC, angela-tran approved these changes

2024-07-09 17:10 UTC, merged