Refactor: `AuthProvider` to `ClaimsProvider`
cal-itp/benefits pull request #2256
Opened 2024-07-31 20:25 UTC by angela-tran

Closes #2233

2024-08-02 23:21 UTC, angela-tran commented
Ready for review

2024-08-02 23:22 UTC, angela-tran commented
Not sure if this one (`authentication providers`) needs to be updated and/or what the right wording would be.

https://github.com/cal-itp/benefits/blob/58abd80eed9e22cc71cadcd4d45059919370ec72/docs/README.md?plain=1#L41

2024-08-05 17:43 UTC, thekaveman commented
> Not sure if this one (`authentication providers`) needs to be updated and/or what the right wording would be.
> 
> https://github.com/cal-itp/benefits/blob/58abd80eed9e22cc71cadcd4d45059919370ec72/docs/README.md?plain=1#L41

I think `claims providers` here is fine?

2024-08-05 20:01 UTC, thekaveman requested changes

2024-08-05 20:49 UTC, lalver1 reviewed
The code changes look good! These were verified:

- [x] For all `EligibilityVerifier`s that with a reference to an `AuthProvider`, confirm those references were maintained, only now the field is called "Claims provider" in the admin interface, `claims_provider` in the database
- [x] Confirm the `Can X auth provider` permissions are removed from the database
- [x] Confirm the `Can X claims provider` permissions are added to the database
- [x] Confirm the Cal-ITP group has `Can [view|change] claims provider` permissions
- [x] Flows using claims from IdG should still work

Just saw a minor typo in `oauth.md`.

2024-08-05 20:55 UTC, angela-tran commented on docs/configuration/oauth.md
> +The [data migration file](./data.md) contains sample values for an `ClaimsProvider` configuration. You can set values for a real Open ID Connect provider in environment variables so that they are use
Thanks! Made that change in [ee3df8ec](https://github.com/cal-itp/benefits/pull/2256/commits/ee3df8ec8bdda588730e10a2e62b28a88202cd5b#diff-6339472682ab7bbe740e47e1193103b337eb1babcc56266cd838a9ca5c051b82R27)

2024-08-05 21:02 UTC, thekaveman approved these changes
This looks great :+1: !!!

2024-08-05 21:14 UTC, merged