Refactor: PaymentProcessor becomes TransitProcessor
cal-itp/benefits pull request #2262
Opened 2024-08-01 00:02 UTC by thekaveman

Closes #2235

2024-08-01 15:48 UTC, thekaveman commented
@angela-tran I don't want to step on your toes with #2256 since we both have migrations...

I think this PR is ready to open for review, but I can rebase it onto yours and deal with the migrations conflicts here if you'd rather.

2024-08-01 16:00 UTC, angela-tran commented
> @angela-tran I don't want to step on your toes with #2256 since we both have migrations...
> 
> I think this PR is ready to open for review, but I can rebase it onto yours and deal with the migrations conflicts here if you'd rather.

Thanks for checking! I'm still working on my PR, so I'm ok if your PR goes in first and I rebase onto `main` and resolve merge conflicts. I might also look over my migrations when I'm done making changes and see if I can combine them into one migration anyways.

In general, I think it's up to each PR to make sure it's working with the latest migrations in `main`.

2024-08-01 23:43 UTC, angela-tran commented
### Things to check locally

* [x]  For fields that were moved to `TransitAgency`, confirm data is migrated
* [x]  Confirm the `Can X payment processor` permissions are removed from the database
* [x]  Confirm the `Can X transit processor` permissions are added to the database

<br/>

> * [ ]  Confirm the Cal-ITP group has `Can [add|change] transit processor` permissions

@thekaveman Did you mean `Can [view|change] transit processor`?

* [x]  Confirm the Cal-ITP group has `Can [view|change] transit processor` permissions

2024-08-01 23:44 UTC, angela-tran requested changes
Code changes look good 👍 

Noticed a small typo

2024-08-01 23:44 UTC, angela-tran commented on benefits/core/migrations/0016_refactor_paymentprocessor_transitprocessor.py
> +                help_text="The abolute URL for the client-side card tokenization library provided by the TransitProcessor."
```suggestion
                help_text="The absolute URL for the client-side card tokenization library provided by the TransitProcessor."
```

2024-08-01 23:44 UTC, angela-tran commented on benefits/core/models.py
> +        help_text="The abolute URL for the client-side card tokenization library provided by the TransitProcessor."
```suggestion
        help_text="The absolute URL for the client-side card tokenization library provided by the TransitProcessor."
```

2024-08-02 00:36 UTC, thekaveman commented on benefits/core/models.py
> +        help_text="The abolute URL for the client-side card tokenization library provided by the TransitProcessor."
Thanks! [`fb35314`](https://github.com/cal-itp/benefits/pull/2262/commits/fb3531410666cee6ee0aba41749d87d635c3b92e)

2024-08-02 00:42 UTC, thekaveman commented on benefits/core/migrations/0016_refactor_paymentprocessor_transitprocessor.py
> +                help_text="The abolute URL for the client-side card tokenization library provided by the TransitProcessor."
Thanks! [8f0f2a7](https://github.com/cal-itp/benefits/pull/2262/commits/8f0f2a7c525e959a843257cbb983cb19ab3f32ff)

2024-08-02 16:07 UTC, lalver1 commented
Looks good to me too!

- [x] For fields that were moved to `TransitAgency`, confirm data is migrated
- [x] Confirm the `Can X payment processor` permissions are removed from the database
- [x] Confirm the `Can X transit processor` permissions are added to the database
- [x] Confirm the Cal-ITP group has `Can [view|change] transit processor` permissions

2024-08-02 16:34 UTC, angela-tran approved these changes

2024-08-02 18:07 UTC, merged