Feat: customize the login form using an environment variable
cal-itp/benefits pull request #2361
Opened 2024-09-11 20:15 UTC by lalver1

2024-09-11 21:14 UTC, machikoyasuda commented on benefits/settings.py
> +SSO_SHOW_FORM_ON_ADMIN_PAGE = os.environ.get("SSO_SHOW_FORM_ON_ADMIN_PAGE", "False").lower() == "true"
https://megalus.github.io/django-google-sso/customize/#hiding-the-login-form

2024-09-11 21:48 UTC, machikoyasuda approved these changes
Tested:
<img width="564" alt="image" src="https://github.com/user-attachments/assets/4df22eb1-4fcc-4b92-99dd-0ffc958c2adb">

2024-09-11 21:53 UTC, angela-tran approved these changes
This LGTM!

2024-09-12 16:12 UTC, angela-tran requested changes
Luis noticed that there is a missing comma in the line above the one he added 😅 so I'm dismissing my review

2024-09-12 16:21 UTC, angela-tran approved these changes

2024-09-12 16:25 UTC, lalver1 commented
It's interesting @angela-tran , looks like commas are not required according to the [terraform docs](https://developer.hashicorp.com/terraform/language/expressions/types#maps-objects) since [app_settings](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#app_settings) are a key-value pair, but it's prob best to include them (it also makes the VS Code syntax highlighting look uniform).

2024-09-12 16:33 UTC, merged