refactor(img): use webp in img instead of png in background
cal-itp/benefits pull request #238
Opened 2021-12-02 08:07 UTC by machikoyasuda

2021-12-03 03:57 UTC, thekaveman requested changes
See my one comment on the alt text.

Maybe it's just me, but this image definitely feels grainier / less high-quality 🤷

2021-12-03 03:57 UTC, thekaveman commented on benefits/core/templates/core/page.html
> +            <img src="{% static page.image.src %}" class="core-image" alt="Rider tapping a debit card to pay for their trip" >
Maybe this commit didn't make it up yet?

Alt tag needs to be `{% translate "core.index.image" context "image alt text" %}`.

Same as how it's done on the Enrollment success image.

2021-12-03 20:27 UTC, machikoyasuda commented
@thekaveman I can remake the WebP photo file to raise the quality a bit.

2021-12-04 00:01 UTC, machikoyasuda commented
Closing for the time being b/c of lack of universal WebP support

2021-12-04 00:01 UTC, closed without merging