Admin: Update admin page titles
cal-itp/benefits pull request #2410
Opened 2024-09-26 16:01 UTC by machikoyasuda

closes #2381 

## What this PR does
- Updates all Administrator app page titles according to what's on https://miro.com/app/board/uXjVKwXyUy0=/ - check the text above the bordered page sections
- Uses Django admin variables or Django template default titles for as much as possible: https://docs.djangoproject.com/en/5.1/ref/contrib/admin/#adminsite-attributes
- Updated anywhere we could use above variables

2024-09-26 17:04 UTC, machikoyasuda commented on benefits/templates/admin/login.html
> -
This is not necessary here, because the `{% extends "admin/login.html" %}` default Django login page's title uses `Log in | site_title`.

2024-09-26 17:05 UTC, machikoyasuda commented on benefits/templates/registration/logged_out.html
>  {% endblock title %}
This `logged_out` page extends from `agency-base`, and _not_ the default Django admin log out template, so it's necessary to explicitly spell out `Logged out`

2024-09-27 14:57 UTC, lalver1 commented
This looks good! I like how the titles are organized now 👍
While testing I did notice that `server_error.html` and `success.html`, for example, did not have the title set. So I'm wondering, would we want to add `title` to the context for the views: `reenrollment_error`, `retry`, `system_error`, `server_error`, `success`. I think this would set the title for these pages since they already inherit from `error-base.html` or `agency-base.html`.

2024-09-30 19:13 UTC, angela-tran requested changes
1 requested change about success / error page titles. The other 2 comments are just notes

2024-09-30 19:13 UTC, angela-tran commented on benefits/in_person/views.py
> +            "title": f"{agency.long_name} | In-person enrollment | {admin_site.site_title}",
I agree with @lalver1 that we want to add this to the context for the error view functions below (`reenrollment_error`, etc.).

Currently, they have no page title:
![image](https://github.com/user-attachments/assets/86085e3f-cd2a-4cc9-b7f5-2173ca3c815d)

2024-09-30 21:24 UTC, machikoyasuda commented on benefits/admin.py
> +    index_title = "Dashboard"
Thanks for documenting this!

2024-09-30 22:37 UTC, machikoyasuda commented
@angela-tran @lalver1 Thanks for the review.
I added code, test updates to cover all those pages I forgot (sys error, server error, re-enrollment error, retry). And I tested them!

I wanted to do the simplest fix for now, as it's the last day of the sprint. But we could make a ticket in the future to refactor like @angela-tran suggested above at a later time.

2024-09-30 22:51 UTC, angela-tran approved these changes
This looks great - thank you @machikoyasuda !

<img src="https://github.com/user-attachments/assets/621b6ba9-3bbf-4cbb-8020-363c57f9c4e6" width="450">

2024-09-30 23:39 UTC, merged