Simplify API check's usage of cert files
cal-itp/benefits pull request #261
Opened 2021-12-09 20:25 UTC by angela-tran

It is not necessary to base64-encode the cert files as a single string.
The workflow will now read the secret, which is expected to be simply the file contents, newlines and all).

2021-12-09 22:24 UTC, angela-tran commented
Oh, good idea with using that branch dropdown. That is nice for testing 👍

2021-12-09 22:57 UTC, angela-tran commented
Thanks for catching those errors @thekaveman. I also realized the code to read the event name was slightly wrong (which is why last night's scheduled run just skipped the job steps) and fixed that.

Here's the first successful run: https://github.com/cal-itp/benefits/actions/runs/1561037010 🎉

2021-12-09 23:44 UTC, thekaveman requested changes
Tiny stylistic change, but otherwise looks good!

2021-12-09 23:44 UTC, thekaveman commented on .github/workflows/check-api.yml
>            APIs to check: \"${{ github.event.inputs.environment }}\""
Let's get rid of the `\"` from the messages here, it clutters up the log message in the Action run, and we already have the `:` separator to distinguish the message label from the value.

2021-12-10 15:40 UTC, thekaveman approved these changes

2021-12-10 16:36 UTC, merged