chore: reflect the sticky settings in Terraform
cal-itp/benefits pull request #693
Opened 2022-06-15 05:47 UTC by afeld

No change to configuration, just moving more things into Terraform.

2022-06-15 16:06 UTC, thekaveman requested changes

2022-06-15 16:06 UTC, thekaveman commented on terraform/app_service.tf
> +      "DJANGO_TRUSTED_ORIGINS",
From [`linux_web_app#sticky_settings`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#sticky_settings):

> [app_setting_names](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#app_setting_names) - (Optional) A list of app_setting names that the Linux Web App will not swap between Slots when a swap operation is triggered.

I think most of these `DJANGO_*` settings should _not_ be sticky, they correspond to the slots.

On this list, the only one that may be the same across slots is `DJANGO_OAUTH_CLIENT_ID` (but even that could change once we finish with #621).

Not on this list, but could be added (they are not currently slot settings):

* `DJANGO_INIT_PATH` - now that we have the mounts normalized for each env, this is the same)
* `DJANGO_OAUTH_CLIENT_NAME` - just the internal app identifier for the OAuth client

2022-06-15 20:44 UTC, afeld commented
The `plan`:

```
      ~ sticky_settings {
          ~ app_setting_names       = [
                # (3 unchanged elements hidden)
                "APPLICATIONINSIGHTS_CONFIGURATION_CONTENT",
              - "APPLICATIONINSIGHTS_CONNECTION_STRING ",
              + "APPLICATIONINSIGHTS_CONNECTION_STRING",
                "ApplicationInsightsAgent_EXTENSION_VERSION",
              - "DJANGO_ALLOWED_HOSTS",
              - "DJANGO_LOG_LEVEL",
              - "DJANGO_OAUTH_AUTHORITY",
                "DJANGO_OAUTH_CLIENT_ID",
              - "DJANGO_SECRET_KEY",
              - "DJANGO_TRUSTED_ORIGINS",
              + "DJANGO_OAUTH_CLIENT_NAME",
              + "DJANGO_INIT_PATH",
                "DiagnosticServices_EXTENSION_VERSION",
                # (7 unchanged elements hidden)
            ]
            # (1 unchanged attribute hidden)
        }
```

Not sure why there was whitespace after `APPLICATIONINSIGHTS_CONNECTION_STRING` (in the state), but it was giving an error when I left it in 🤷

2022-06-15 23:08 UTC, thekaveman approved these changes
👍

2022-06-16 14:23 UTC, merged

2022-06-22 23:47 UTC, thekaveman commented
@afeld Maybe I'm confused... this seems to have done exactly the opposite of what I thought we wanted? Here's a screenshot from the `dev` slot - the ✔️ indicates it is a Slot setting (so varies by slot), and these are all the ones that should actually be _sticky_ (not vary) -- right??

![image](https://user-images.githubusercontent.com/1783439/175178860-e20e2a17-f941-48c6-8659-9f79696d9ed9.png)

2022-06-24 00:02 UTC, afeld commented
Attempting to clarify in https://github.com/cal-itp/benefits/pull/736.