Feat: IAL2 help copy
cal-itp/benefits pull request #708
Opened 2022-06-16 23:00 UTC by angela-tran

Closes #705

Updates a body paragraph in "What is Cal-ITP Benefits?" section to say Login.gov will verify age.

Adds a section for "How do I verify my identity on Login.gov?".

Updates made using finalized English copy and any Spanish copy update that was available.

2022-06-16 23:20 UTC, angela-tran commented
Ready for review

2022-06-17 00:55 UTC, thekaveman requested changes

2022-06-17 00:55 UTC, thekaveman commented on benefits/locale/en/LC_MESSAGES/django.po
> +"We partner with the Login.gov to confirm age for age-based discounts, and we "
delete extra `the`

```diff
-We partner with the Login.gov
+We partner with Login.gov
```

2022-06-17 16:36 UTC, angela-tran commented on benefits/locale/en/LC_MESSAGES/django.po
> +"We partner with the Login.gov to confirm age for age-based discounts, and we "
Ah, thanks for catching that

2022-06-17 17:23 UTC, thekaveman approved these changes

2022-06-17 17:25 UTC, merged